# -*- coding: utf-8 -*-
"""helloworld.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jtEzn0ivURQnmJFfW3nop26UgYD6OUcd
"""

# ini adalah contoh fungsi Python yang digunakan untuk mencetak

print("Hello World")