# -*- coding: utf-8 -*-
"""string.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mqp9Kl0YxorcwZDF7A6V2LZHDz9dUw5O
"""

# string

name = 'John Doe' message = "John Doe belajar bahasa python di Belajarpython"
print ("name[0]: ", name[0])
print ("message[1:4]: ", message[1:4])