# -*- coding: utf-8 -*-
"""tuple.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PbS6VYDZx_GytlvLcyl2UVEuHD9RcFDL
"""

#Contoh sederhana pembuatan tuple pada bahasa pemrograman python

tup1 = ('fisika', 'kimia', 1993, 2017)
tup2 = (1, 2, 3, 4, 5 )
tup3 = "a", "b", "c", "d"


#Cara mengakses nilai tuple

tup1 = ('fisika', 'kimia', 1993, 2017)
tup2 = (1, 2, 3, 4, 5, 6, 7 )

print ("tup1[0]: ", tup1[0])
print ("tup2[1:5]: ", tup2[1:5])
Setelah Anda mengeksekusi kode diatas, hasilnya akan seperti dibawah ini :

tup1[0]: fisika tup2[1:5]: (2, 3, 4, 5)

#Cara update nilai tuple
tup1 = (12, 34.56)
tup2 = ('abc', 'xyz')

# Aksi seperti dibawah ini tidak bisa dilakukan pada tuple python

# Karena memang nilai pada tuple python tidak bisa diubah

# tup1[0] = 100;

# Jadi, buatlah tuple baru sebagai berikut

tup3 = tup1 + tup2
print (tup3)